version: '3.8'

services:
  homelab-idp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelab-idp
    restart: unless-stopped
    ports:
      - "8300:4000" # Host port 8300 -> Container port 4000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - shared_net

networks:
  shared_net:
    external: true
